name: hitl-lithium
channels:
  - conda-forge
  - defaults
dependencies:
  # Python version
  - python=3.9
  
  # Core scientific computing
  - numpy=1.24.3
  - pandas=2.0.3
  - scipy=1.11.1
  
  # Machine learning
  - scikit-learn=1.3.0
  - optuna=3.2.0
  - shap=0.42.1
  
  # Optimization
  - platypus-opt=1.0.4
  
  # Visualization
  - matplotlib=3.7.2
  - seaborn=0.12.2
  
  # Jupyter environment
  - jupyter=1.0.0
  - notebook=7.0.2
  - ipykernel=6.25.0
  
  # Progress tracking
  - tqdm=4.65.0
  
  # Additional utilities
  - openpyxl=3.1.2  # For Excel file reading
  - xlrd=2.0.1      # For older Excel files
  
  # Development tools (optional)
  - pip=23.2.1
  - pytest=7.4.0
  - black=23.7.0
  - flake8=6.0.0
  
  # Additional packages via pip
  - pip:
    - platypus-opt==1.0.4  # Ensure correct version
    - shap==0.42.1         # Ensure correct version 